/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Alt = {
  id?: string;
  en?: string;
};

export type CanonicalUrl = {
  id?: string;
  en?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: Array<
    {
      _key: string;
    } & Link
  >;
  footer?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organizationName?: string;
  legalName?: string;
  tagline?: LocaleString;
  logo?: ImageWithAlt;
  homePage?: PageReference;
  footerText?: LocaleText;
  disclaimer?: LocaleText;
  email?: string;
  phone?: string;
  address?: Address;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  defaultSeo?: Seo;
  analytics?: {
    cloudflareWebAnalyticsToken?: string;
    ga4MeasurementId?: string;
  };
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: LocaleString;
  metaDescription?: LocaleText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
  canonicalUrl?: CanonicalUrl;
};

export type Address = {
  _type: "address";
  street?: string;
  city?: string;
  province?: string;
  postalCode?: string;
  country?: string;
  mapUrl?: string;
};

export type LocaleText = {
  _type: "localeText";
  id?: string;
  en?: string;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: Alt;
};

export type LocaleString = {
  _type: "localeString";
  id?: string;
  en?: string;
};

export type ImageTextSection = {
  _type: "imageTextSection";
  heading?: LocaleString;
  body?: LocaleBlockContent;
  image?: ImageWithAlt;
  imagePosition?: "left" | "right";
};

export type FeatureListSection = {
  _type: "featureListSection";
  heading?: RequiredLocaleString;
  intro?: LocaleText;
  items?: Array<{
    title?: RequiredLocaleString;
    description?: LocaleText;
    _type: "featureItem";
    _key: string;
  }>;
};

export type CtaSection = {
  _type: "ctaSection";
  heading?: RequiredLocaleString;
  text?: LocaleText;
  cta?: Link;
};

export type RichTextSection = {
  _type: "richTextSection";
  heading?: LocaleString;
  body?: RequiredLocaleBlockContent;
};

export type HeroSection = {
  _type: "heroSection";
  heading?: RequiredLocaleString;
  subheading?: LocaleText;
  image?: ImageWithAlt;
  ctas?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Link = {
  _type: "link";
  label?: RequiredLocaleString;
  linkType?: "page" | "path" | "external";
  page?: PageReference;
  path?: string;
  url?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: RequiredLocaleString;
  slug?: LocaleSlug;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & FeatureListSection)
    | ({
        _key: string;
      } & ImageTextSection)
  >;
  seo?: Seo;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  id?: BlockContent;
  en?: BlockContent;
};

export type RequiredLocaleString = {
  _type: "requiredLocaleString";
  id?: string;
  en?: string;
};

export type RequiredLocaleBlockContent = {
  _type: "requiredLocaleBlockContent";
  id?: BlockContent;
  en?: BlockContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type LocaleSlug = {
  _type: "localeSlug";
  id?: string;
  en?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform?:
    "LinkedIn" | "X" | "Instagram" | "Facebook" | "YouTube" | "WhatsApp";
  url?: string;
};

export type RequiredLocaleText = {
  _type: "requiredLocaleText";
  id?: string;
  en?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Alt
  | CanonicalUrl
  | Navigation
  | PageReference
  | SiteSettings
  | SanityImageAssetReference
  | Seo
  | Address
  | LocaleText
  | ImageWithAlt
  | LocaleString
  | ImageTextSection
  | FeatureListSection
  | CtaSection
  | RichTextSection
  | HeroSection
  | BlockContent
  | Link
  | Page
  | LocaleBlockContent
  | RequiredLocaleString
  | RequiredLocaleBlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | LocaleSlug
  | SocialLink
  | RequiredLocaleText
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  organizationName, legalName, tagline, logo, footerText, disclaimer,  email, phone, address, socialLinks, defaultSeo}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      organizationName: null;
      legalName: null;
      tagline: null;
      logo: null;
      footerText: null;
      disclaimer: null;
      email: null;
      phone: null;
      address: null;
      socialLinks: null;
      defaultSeo: null;
    }
  | {
      organizationName: string | null;
      legalName: string | null;
      tagline: LocaleString | null;
      logo: ImageWithAlt | null;
      footerText: LocaleText | null;
      disclaimer: LocaleText | null;
      email: string | null;
      phone: string | null;
      address: Address | null;
      socialLinks: Array<
        {
          _key: string;
        } & SocialLink
      > | null;
      defaultSeo: Seo | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_id == "navigation"][0]{  "header": header[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref },  "footer": footer[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref }}
export type NAVIGATION_QUERY_RESULT =
  | {
      header: null;
      footer: null;
    }
  | {
      header: Array<{
        _key: string;
        label: RequiredLocaleString | null;
        linkType: "external" | "page" | "path" | null;
        path: string | null;
        url: string | null;
        pageSlug: LocaleSlug | null;
        isHomePage: boolean | false | true;
      }> | null;
      footer: Array<{
        _key: string;
        label: RequiredLocaleString | null;
        linkType: "external" | "page" | "path" | null;
        path: string | null;
        url: string | null;
        pageSlug: LocaleSlug | null;
        isHomePage: boolean | false | true;
      }> | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "siteSettings"][0].homePage->{   _id, title, slug, seo,  sections[]{    ...,    _type == "heroSection" => { "ctas": ctas[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } },    _type == "ctaSection" => { "cta": cta{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } }  } }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  seo: Seo | null;
  sections: Array<
    | {
        _key: string;
        _type: "ctaSection";
        heading?: RequiredLocaleString;
        text?: LocaleText;
        cta: {
          _key: null;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        } | null;
      }
    | {
        _key: string;
        _type: "featureListSection";
        heading?: RequiredLocaleString;
        intro?: LocaleText;
        items?: Array<{
          title?: RequiredLocaleString;
          description?: LocaleText;
          _type: "featureItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "heroSection";
        heading?: RequiredLocaleString;
        subheading?: LocaleText;
        image?: ImageWithAlt;
        ctas: Array<{
          _key: string;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        }> | null;
      }
    | {
        _key: string;
        _type: "imageTextSection";
        heading?: LocaleString;
        body?: LocaleBlockContent;
        image?: ImageWithAlt;
        imagePosition?: "left" | "right";
      }
    | {
        _key: string;
        _type: "richTextSection";
        heading?: LocaleString;
        body?: RequiredLocaleBlockContent;
      }
  > | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[  _type == "page" && slug[$locale] == $slug && _id != *[_id == "siteSettings"][0].homePage._ref][0]{   _id, title, slug, seo,  sections[]{    ...,    _type == "heroSection" => { "ctas": ctas[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } },    _type == "ctaSection" => { "cta": cta{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } }  } }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  seo: Seo | null;
  sections: Array<
    | {
        _key: string;
        _type: "ctaSection";
        heading?: RequiredLocaleString;
        text?: LocaleText;
        cta: {
          _key: null;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        } | null;
      }
    | {
        _key: string;
        _type: "featureListSection";
        heading?: RequiredLocaleString;
        intro?: LocaleText;
        items?: Array<{
          title?: RequiredLocaleString;
          description?: LocaleText;
          _type: "featureItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "heroSection";
        heading?: RequiredLocaleString;
        subheading?: LocaleText;
        image?: ImageWithAlt;
        ctas: Array<{
          _key: string;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        }> | null;
      }
    | {
        _key: string;
        _type: "imageTextSection";
        heading?: LocaleString;
        body?: LocaleBlockContent;
        image?: ImageWithAlt;
        imagePosition?: "left" | "right";
      }
    | {
        _key: string;
        _type: "richTextSection";
        heading?: LocaleString;
        body?: RequiredLocaleBlockContent;
      }
  > | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_BY_ANY_SLUG_QUERY
// Query: *[  _type == "page" && $slug in [slug.id, slug.en] && _id != *[_id == "siteSettings"][0].homePage._ref][0]{ slug }
export type PAGE_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[  _type == "page" && defined(slug) && _id != *[_id == "siteSettings"][0].homePage._ref]{ slug }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_id == "siteSettings"][0]{\n  organizationName, legalName, tagline, logo, footerText, disclaimer,\n  email, phone, address, socialLinks, defaultSeo\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_id == "navigation"][0]{\n  "header": header[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n },\n  "footer": footer[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n }\n}': NAVIGATION_QUERY_RESULT;
    '*[_id == "siteSettings"][0].homePage->{ \n  _id, title, slug, seo,\n  sections[]{\n    ...,\n    _type == "heroSection" => { "ctas": ctas[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } },\n    _type == "ctaSection" => { "cta": cta{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } }\n  }\n }': HOME_PAGE_QUERY_RESULT;
    '*[\n  _type == "page" && slug[$locale] == $slug && _id != *[_id == "siteSettings"][0].homePage._ref\n][0]{ \n  _id, title, slug, seo,\n  sections[]{\n    ...,\n    _type == "heroSection" => { "ctas": ctas[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } },\n    _type == "ctaSection" => { "cta": cta{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } }\n  }\n }': PAGE_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "page" && $slug in [slug.id, slug.en] && _id != *[_id == "siteSettings"][0].homePage._ref\n][0]{ slug }': PAGE_BY_ANY_SLUG_QUERY_RESULT;
    '*[\n  _type == "page" && defined(slug) && _id != *[_id == "siteSettings"][0].homePage._ref\n]{ slug }': PAGE_SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
