/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Alt = {
  id?: string;
  en?: string;
};

export type CanonicalUrl = {
  id?: string;
  en?: string;
};

export type Credential = {
  _id: string;
  _type: "credential";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  approvedForDisplay?: boolean;
  title?: RequiredLocaleString;
  issuer?: string;
  year?: number;
  logo?: ImageWithAlt;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: Alt;
};

export type RequiredLocaleString = {
  _type: "requiredLocaleString";
  id?: string;
  en?: string;
};

export type JobOpening = {
  _id: string;
  _type: "jobOpening";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  isOpen?: boolean;
  title?: RequiredLocaleString;
  slug?: LocaleSlug;
  location?: RequiredLocaleString;
  employmentType?: "fullTime" | "partTime" | "contract" | "internship";
  deadline?: string;
  description?: RequiredLocaleBlockContent;
  applyUrl?: string;
  seo?: Seo;
};

export type RequiredLocaleBlockContent = {
  _type: "requiredLocaleBlockContent";
  id?: BlockContent;
  en?: BlockContent;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type OfficeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "office";
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: LocaleSlug;
  position?: RequiredLocaleString;
  group?: "board" | "leadership" | "partner" | "team";
  photo?: ImageWithAlt;
  bio?: LocaleBlockContent;
  credentials?: Array<{
    kind?: "education" | "certification" | "license";
    title?: RequiredLocaleString;
    year?: number;
    _type: "personCredential";
    _key: string;
  }>;
  languages?: Array<string>;
  email?: string;
  linkedin?: string;
  order?: number;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  office?: OfficeReference;
  seo?: Seo;
};

export type Office = {
  _id: string;
  _type: "office";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: RequiredLocaleString;
  address?: Address;
  phone?: string;
  email?: string;
  order?: number;
};

export type Address = {
  _type: "address";
  street?: string;
  city?: string;
  province?: string;
  postalCode?: string;
  country?: string;
  mapUrl?: string;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  id?: BlockContent;
  en?: BlockContent;
};

export type LocaleSlug = {
  _type: "localeSlug";
  id?: string;
  en?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type Insight = {
  _id: string;
  _type: "insight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: RequiredLocaleString;
  slug?: LocaleSlug;
  category?: "article" | "news" | "pressRelease" | "publication" | "update";
  publishedAt?: string;
  excerpt?: RequiredLocaleText;
  body?: RequiredLocaleBlockContent;
  attachment?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  authors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  seo?: Seo;
};

export type RequiredLocaleText = {
  _type: "requiredLocaleText";
  id?: string;
  en?: string;
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clientConsent?: boolean;
  consentReference?: string;
  title?: RequiredLocaleString;
  slug?: LocaleSlug;
  client?: RequiredLocaleString;
  year?: number;
  summary?: RequiredLocaleText;
  challenge?: RequiredLocaleBlockContent;
  approach?: RequiredLocaleBlockContent;
  outcome?: RequiredLocaleBlockContent;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  industries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  seo?: Seo;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: RequiredLocaleString;
  slug?: LocaleSlug;
  summary?: RequiredLocaleText;
  body?: LocaleBlockContent;
  order?: number;
  seo?: Seo;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: RequiredLocaleString;
  slug?: LocaleSlug;
  summary?: RequiredLocaleText;
  body?: LocaleBlockContent;
  order?: number;
  keyContacts?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  industries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: LocaleString;
  metaDescription?: LocaleText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
  canonicalUrl?: CanonicalUrl;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: Array<
    {
      _key: string;
    } & Link
  >;
  footer?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organizationName?: string;
  legalName?: string;
  tagline?: LocaleString;
  logo?: ImageWithAlt;
  homePage?: PageReference;
  footerText?: LocaleText;
  disclaimer?: LocaleText;
  email?: string;
  phone?: string;
  address?: Address;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  defaultSeo?: Seo;
  analytics?: {
    cloudflareWebAnalyticsToken?: string;
    ga4MeasurementId?: string;
  };
};

export type LocaleText = {
  _type: "localeText";
  id?: string;
  en?: string;
};

export type LocaleString = {
  _type: "localeString";
  id?: string;
  en?: string;
};

export type CredentialListSection = {
  _type: "credentialListSection";
  heading?: RequiredLocaleString;
  intro?: LocaleText;
};

export type ImageTextSection = {
  _type: "imageTextSection";
  heading?: LocaleString;
  body?: LocaleBlockContent;
  image?: ImageWithAlt;
  imagePosition?: "left" | "right";
};

export type FeatureListSection = {
  _type: "featureListSection";
  heading?: RequiredLocaleString;
  intro?: LocaleText;
  items?: Array<{
    title?: RequiredLocaleString;
    description?: LocaleText;
    _type: "featureItem";
    _key: string;
  }>;
};

export type CtaSection = {
  _type: "ctaSection";
  heading?: RequiredLocaleString;
  text?: LocaleText;
  cta?: Link;
};

export type RichTextSection = {
  _type: "richTextSection";
  heading?: LocaleString;
  body?: RequiredLocaleBlockContent;
};

export type HeroSection = {
  _type: "heroSection";
  heading?: RequiredLocaleString;
  subheading?: LocaleText;
  image?: ImageWithAlt;
  ctas?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Link = {
  _type: "link";
  label?: RequiredLocaleString;
  linkType?: "page" | "path" | "external";
  page?: PageReference;
  path?: string;
  url?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: RequiredLocaleString;
  slug?: LocaleSlug;
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & FeatureListSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & CredentialListSection)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SocialLink = {
  _type: "socialLink";
  platform?:
    "LinkedIn" | "X" | "Instagram" | "Facebook" | "YouTube" | "WhatsApp";
  url?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Alt
  | CanonicalUrl
  | Credential
  | SanityImageAssetReference
  | ImageWithAlt
  | RequiredLocaleString
  | JobOpening
  | RequiredLocaleBlockContent
  | ServiceReference
  | OfficeReference
  | Person
  | Office
  | Address
  | LocaleBlockContent
  | LocaleSlug
  | SanityFileAssetReference
  | PersonReference
  | Insight
  | RequiredLocaleText
  | IndustryReference
  | CaseStudy
  | Industry
  | Service
  | Seo
  | Navigation
  | PageReference
  | SiteSettings
  | LocaleText
  | LocaleString
  | CredentialListSection
  | ImageTextSection
  | FeatureListSection
  | CtaSection
  | RichTextSection
  | HeroSection
  | BlockContent
  | Link
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/lib/sanity/collections/caseStudy.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[_type == "caseStudy" && clientConsent == true && defined(slug)]  | order(year desc, title.id asc){ _id, title, slug, summary, client, year }
export type CASE_STUDIES_QUERY_RESULT = Array<{
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug;
  summary: RequiredLocaleText | null;
  client: RequiredLocaleString | null;
  year: number | null;
}>;

// Source: ../web/lib/sanity/collections/caseStudy.ts
// Variable: CASE_STUDY_BY_SLUG_QUERY
// Query: *[  _type == "caseStudy" && clientConsent == true && slug[$locale] == $slug][0]{  _id, title, slug, summary, client, year, challenge, approach, outcome, seo,  "services": services[defined(@->slug)]->{ _id, title, slug, summary },  "industries": industries[defined(@->slug)]->{ _id, title, slug, summary }}
export type CASE_STUDY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  summary: RequiredLocaleText | null;
  client: RequiredLocaleString | null;
  year: number | null;
  challenge: RequiredLocaleBlockContent | null;
  approach: RequiredLocaleBlockContent | null;
  outcome: RequiredLocaleBlockContent | null;
  seo: Seo | null;
  services: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
  }> | null;
  industries: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
  }> | null;
} | null;

// Source: ../web/lib/sanity/collections/caseStudy.ts
// Variable: CASE_STUDY_BY_ANY_SLUG_QUERY
// Query: *[  _type == "caseStudy" && clientConsent == true && $slug in [slug.id, slug.en]][0]{ slug }
export type CASE_STUDY_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/collections/caseStudy.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[  _type == "caseStudy" && clientConsent == true && defined(slug)]{ slug }
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug;
}>;

// Source: ../web/lib/sanity/collections/industry.ts
// Variable: INDUSTRIES_QUERY
// Query: *[_type == "industry" && defined(slug)]  | order(order asc, title.id asc){ _id, title, slug, summary }
export type INDUSTRIES_QUERY_RESULT = Array<{
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug;
  summary: RequiredLocaleText | null;
}>;

// Source: ../web/lib/sanity/collections/industry.ts
// Variable: INDUSTRY_BY_SLUG_QUERY
// Query: *[_type == "industry" && slug[$locale] == $slug][0]{  _id, title, slug, summary, body, seo,  "services": *[_type == "service" && references(^._id)] | order(order asc){ _id, title, slug, summary },  "caseStudies": *[_type == "caseStudy" && clientConsent == true && references(^._id)] | order(year desc){    _id, title, slug, summary, client, year  }}
export type INDUSTRY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  summary: RequiredLocaleText | null;
  body: LocaleBlockContent | null;
  seo: Seo | null;
  services: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
  }>;
  caseStudies: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
    client: RequiredLocaleString | null;
    year: number | null;
  }>;
} | null;

// Source: ../web/lib/sanity/collections/industry.ts
// Variable: INDUSTRY_BY_ANY_SLUG_QUERY
// Query: *[  _type == "industry" && $slug in [slug.id, slug.en]][0]{ slug }
export type INDUSTRY_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/collections/industry.ts
// Variable: INDUSTRY_SLUGS_QUERY
// Query: *[_type == "industry" && defined(slug)]{ slug }
export type INDUSTRY_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug;
}>;

// Source: ../web/lib/sanity/collections/insight.ts
// Variable: INSIGHTS_QUERY
// Query: *[_type == "insight" && defined(slug)]  | order(publishedAt desc, _createdAt desc){ _id, title, slug, excerpt, category, publishedAt }
export type INSIGHTS_QUERY_RESULT = Array<{
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug;
  excerpt: RequiredLocaleText | null;
  category:
    "article" | "news" | "pressRelease" | "publication" | "update" | null;
  publishedAt: string | null;
}>;

// Source: ../web/lib/sanity/collections/insight.ts
// Variable: INSIGHT_BY_SLUG_QUERY
// Query: *[_type == "insight" && slug[$locale] == $slug][0]{  _id, title, slug, excerpt, category, publishedAt, body, seo,  "attachmentUrl": attachment.asset->url,  "authors": authors[defined(@->slug)]->{ _id, name, slug, position, group, photo },  "services": services[defined(@->slug)]->{ _id, title, slug, summary }}
export type INSIGHT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  excerpt: RequiredLocaleText | null;
  category:
    "article" | "news" | "pressRelease" | "publication" | "update" | null;
  publishedAt: string | null;
  body: RequiredLocaleBlockContent | null;
  seo: Seo | null;
  attachmentUrl: string | null;
  authors: Array<{
    _id: string;
    name: string | null;
    slug: LocaleSlug | null;
    position: RequiredLocaleString | null;
    group: "board" | "leadership" | "partner" | "team" | null;
    photo: ImageWithAlt | null;
  }> | null;
  services: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
  }> | null;
} | null;

// Source: ../web/lib/sanity/collections/insight.ts
// Variable: INSIGHT_BY_ANY_SLUG_QUERY
// Query: *[  _type == "insight" && $slug in [slug.id, slug.en]][0]{ slug }
export type INSIGHT_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/collections/insight.ts
// Variable: INSIGHT_SLUGS_QUERY
// Query: *[_type == "insight" && defined(slug)]{ slug }
export type INSIGHT_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug;
}>;

// Source: ../web/lib/sanity/collections/jobOpening.ts
// Variable: JOB_OPENINGS_QUERY
// Query: *[_type == "jobOpening" && isOpen == true && defined(slug)]  | order(_createdAt desc){ _id, title, slug, location, employmentType, deadline }
export type JOB_OPENINGS_QUERY_RESULT = Array<{
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug;
  location: RequiredLocaleString | null;
  employmentType: "contract" | "fullTime" | "internship" | "partTime" | null;
  deadline: string | null;
}>;

// Source: ../web/lib/sanity/collections/jobOpening.ts
// Variable: JOB_OPENING_BY_SLUG_QUERY
// Query: *[  _type == "jobOpening" && isOpen == true && slug[$locale] == $slug][0]{ _id, title, slug, location, employmentType, deadline, description, applyUrl, seo }
export type JOB_OPENING_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  location: RequiredLocaleString | null;
  employmentType: "contract" | "fullTime" | "internship" | "partTime" | null;
  deadline: string | null;
  description: RequiredLocaleBlockContent | null;
  applyUrl: string | null;
  seo: Seo | null;
} | null;

// Source: ../web/lib/sanity/collections/jobOpening.ts
// Variable: JOB_OPENING_BY_ANY_SLUG_QUERY
// Query: *[  _type == "jobOpening" && isOpen == true && $slug in [slug.id, slug.en]][0]{ slug }
export type JOB_OPENING_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/collections/jobOpening.ts
// Variable: JOB_OPENING_SLUGS_QUERY
// Query: *[  _type == "jobOpening" && isOpen == true && defined(slug)]{ slug }
export type JOB_OPENING_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug;
}>;

// Source: ../web/lib/sanity/collections/office.ts
// Variable: OFFICES_QUERY
// Query: *[_type == "office"]  | order(order asc, name.id asc){ _id, name, address, phone, email }
export type OFFICES_QUERY_RESULT = Array<{
  _id: string;
  name: RequiredLocaleString | null;
  address: Address | null;
  phone: string | null;
  email: string | null;
}>;

// Source: ../web/lib/sanity/collections/person.ts
// Variable: PEOPLE_QUERY
// Query: *[_type == "person" && defined(slug)]  | order(order asc, name asc){ _id, name, slug, position, group, photo }
export type PEOPLE_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: LocaleSlug;
  position: RequiredLocaleString | null;
  group: "board" | "leadership" | "partner" | "team" | null;
  photo: ImageWithAlt | null;
}>;

// Source: ../web/lib/sanity/collections/person.ts
// Variable: PERSON_BY_SLUG_QUERY
// Query: *[_type == "person" && slug[$locale] == $slug][0]{  _id, name, slug, position, group, photo, bio, credentials, languages, email, linkedin, seo,  "services": services[defined(@->slug)]->{ _id, title, slug, summary },  "office": office->{ name, address, phone, email },  "insights": *[_type == "insight" && references(^._id)] | order(publishedAt desc)[0...3]{    _id, title, slug, excerpt, category, publishedAt  }}
export type PERSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: LocaleSlug | null;
  position: RequiredLocaleString | null;
  group: "board" | "leadership" | "partner" | "team" | null;
  photo: ImageWithAlt | null;
  bio: LocaleBlockContent | null;
  credentials: Array<{
    kind?: "certification" | "education" | "license";
    title?: RequiredLocaleString;
    year?: number;
    _type: "personCredential";
    _key: string;
  }> | null;
  languages: Array<string> | null;
  email: string | null;
  linkedin: string | null;
  seo: Seo | null;
  services: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
  }> | null;
  office: {
    name: RequiredLocaleString | null;
    address: Address | null;
    phone: string | null;
    email: string | null;
  } | null;
  insights: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    excerpt: RequiredLocaleText | null;
    category:
      "article" | "news" | "pressRelease" | "publication" | "update" | null;
    publishedAt: string | null;
  }>;
} | null;

// Source: ../web/lib/sanity/collections/person.ts
// Variable: PERSON_BY_ANY_SLUG_QUERY
// Query: *[  _type == "person" && $slug in [slug.id, slug.en]][0]{ slug }
export type PERSON_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/collections/person.ts
// Variable: PERSON_SLUGS_QUERY
// Query: *[_type == "person" && defined(slug)]{ slug }
export type PERSON_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug;
}>;

// Source: ../web/lib/sanity/collections/service.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service" && defined(slug)]  | order(order asc, title.id asc){ _id, title, slug, summary }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug;
  summary: RequiredLocaleText | null;
}>;

// Source: ../web/lib/sanity/collections/service.ts
// Variable: SERVICE_BY_SLUG_QUERY
// Query: *[_type == "service" && slug[$locale] == $slug][0]{  _id, title, slug, summary, body, seo,  "keyContacts": keyContacts[defined(@->slug)]->{ _id, name, slug, position, group, photo },  "industries": industries[defined(@->slug)]->{ _id, title, slug, summary },  "caseStudies": *[_type == "caseStudy" && clientConsent == true && references(^._id)] | order(year desc){    _id, title, slug, summary, client, year  },  "insights": *[_type == "insight" && references(^._id)] | order(publishedAt desc)[0...3]{    _id, title, slug, excerpt, category, publishedAt  }}
export type SERVICE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  summary: RequiredLocaleText | null;
  body: LocaleBlockContent | null;
  seo: Seo | null;
  keyContacts: Array<{
    _id: string;
    name: string | null;
    slug: LocaleSlug | null;
    position: RequiredLocaleString | null;
    group: "board" | "leadership" | "partner" | "team" | null;
    photo: ImageWithAlt | null;
  }> | null;
  industries: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
  }> | null;
  caseStudies: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    summary: RequiredLocaleText | null;
    client: RequiredLocaleString | null;
    year: number | null;
  }>;
  insights: Array<{
    _id: string;
    title: RequiredLocaleString | null;
    slug: LocaleSlug | null;
    excerpt: RequiredLocaleText | null;
    category:
      "article" | "news" | "pressRelease" | "publication" | "update" | null;
    publishedAt: string | null;
  }>;
} | null;

// Source: ../web/lib/sanity/collections/service.ts
// Variable: SERVICE_BY_ANY_SLUG_QUERY
// Query: *[  _type == "service" && $slug in [slug.id, slug.en]][0]{ slug }
export type SERVICE_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/collections/service.ts
// Variable: SERVICE_SLUGS_QUERY
// Query: *[_type == "service" && defined(slug)]{ slug }
export type SERVICE_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug;
}>;

// Source: ../web/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  organizationName, legalName, tagline, logo, footerText, disclaimer,  email, phone, address, socialLinks, defaultSeo}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      organizationName: null;
      legalName: null;
      tagline: null;
      logo: null;
      footerText: null;
      disclaimer: null;
      email: null;
      phone: null;
      address: null;
      socialLinks: null;
      defaultSeo: null;
    }
  | {
      organizationName: null;
      legalName: null;
      tagline: null;
      logo: ImageWithAlt | null;
      footerText: null;
      disclaimer: null;
      email: null;
      phone: null;
      address: null;
      socialLinks: null;
      defaultSeo: null;
    }
  | {
      organizationName: null;
      legalName: null;
      tagline: null;
      logo: null;
      footerText: null;
      disclaimer: null;
      email: string | null;
      phone: null;
      address: null;
      socialLinks: null;
      defaultSeo: null;
    }
  | {
      organizationName: null;
      legalName: null;
      tagline: null;
      logo: null;
      footerText: null;
      disclaimer: null;
      email: string | null;
      phone: string | null;
      address: Address | null;
      socialLinks: null;
      defaultSeo: null;
    }
  | {
      organizationName: string | null;
      legalName: string | null;
      tagline: LocaleString | null;
      logo: ImageWithAlt | null;
      footerText: LocaleText | null;
      disclaimer: LocaleText | null;
      email: string | null;
      phone: string | null;
      address: Address | null;
      socialLinks: Array<
        {
          _key: string;
        } & SocialLink
      > | null;
      defaultSeo: Seo | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_id == "navigation"][0]{  "header": header[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref },  "footer": footer[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref }}
export type NAVIGATION_QUERY_RESULT =
  | {
      header: null;
      footer: null;
    }
  | {
      header: Array<{
        _key: string;
        label: RequiredLocaleString | null;
        linkType: "external" | "page" | "path" | null;
        path: string | null;
        url: string | null;
        pageSlug: LocaleSlug | null;
        isHomePage: boolean | false | true;
      }> | null;
      footer: Array<{
        _key: string;
        label: RequiredLocaleString | null;
        linkType: "external" | "page" | "path" | null;
        path: string | null;
        url: string | null;
        pageSlug: LocaleSlug | null;
        isHomePage: boolean | false | true;
      }> | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "siteSettings"][0].homePage->{   _id, title, slug, seo,  sections[]{    ...,    _type == "heroSection" => { "ctas": ctas[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } },    _type == "ctaSection" => { "cta": cta{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } },    _type == "credentialListSection" => {      "credentials": *[_type == "credential" && approvedForDisplay == true] | order(order asc, year desc){        _id, title, issuer, year, logo      }    }  } }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  seo: Seo | null;
  sections: Array<
    | {
        _key: string;
        _type: "credentialListSection";
        heading?: RequiredLocaleString;
        intro?: LocaleText;
        credentials: Array<{
          _id: string;
          title: RequiredLocaleString | null;
          issuer: string | null;
          year: number | null;
          logo: ImageWithAlt | null;
        }>;
      }
    | {
        _key: string;
        _type: "ctaSection";
        heading?: RequiredLocaleString;
        text?: LocaleText;
        cta: {
          _key: null;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        } | null;
      }
    | {
        _key: string;
        _type: "featureListSection";
        heading?: RequiredLocaleString;
        intro?: LocaleText;
        items?: Array<{
          title?: RequiredLocaleString;
          description?: LocaleText;
          _type: "featureItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "heroSection";
        heading?: RequiredLocaleString;
        subheading?: LocaleText;
        image?: ImageWithAlt;
        ctas: Array<{
          _key: string;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        }> | null;
      }
    | {
        _key: string;
        _type: "imageTextSection";
        heading?: LocaleString;
        body?: LocaleBlockContent;
        image?: ImageWithAlt;
        imagePosition?: "left" | "right";
      }
    | {
        _key: string;
        _type: "richTextSection";
        heading?: LocaleString;
        body?: RequiredLocaleBlockContent;
      }
  > | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[  _type == "page" && slug[$locale] == $slug && _id != *[_id == "siteSettings"][0].homePage._ref][0]{   _id, title, slug, seo,  sections[]{    ...,    _type == "heroSection" => { "ctas": ctas[]{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } },    _type == "ctaSection" => { "cta": cta{   _key, label, linkType, path, url,  "pageSlug": page->slug,  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref } },    _type == "credentialListSection" => {      "credentials": *[_type == "credential" && approvedForDisplay == true] | order(order asc, year desc){        _id, title, issuer, year, logo      }    }  } }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: RequiredLocaleString | null;
  slug: LocaleSlug | null;
  seo: Seo | null;
  sections: Array<
    | {
        _key: string;
        _type: "credentialListSection";
        heading?: RequiredLocaleString;
        intro?: LocaleText;
        credentials: Array<{
          _id: string;
          title: RequiredLocaleString | null;
          issuer: string | null;
          year: number | null;
          logo: ImageWithAlt | null;
        }>;
      }
    | {
        _key: string;
        _type: "ctaSection";
        heading?: RequiredLocaleString;
        text?: LocaleText;
        cta: {
          _key: null;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        } | null;
      }
    | {
        _key: string;
        _type: "featureListSection";
        heading?: RequiredLocaleString;
        intro?: LocaleText;
        items?: Array<{
          title?: RequiredLocaleString;
          description?: LocaleText;
          _type: "featureItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "heroSection";
        heading?: RequiredLocaleString;
        subheading?: LocaleText;
        image?: ImageWithAlt;
        ctas: Array<{
          _key: string;
          label: RequiredLocaleString | null;
          linkType: "external" | "page" | "path" | null;
          path: string | null;
          url: string | null;
          pageSlug: LocaleSlug | null;
          isHomePage: boolean | false | true;
        }> | null;
      }
    | {
        _key: string;
        _type: "imageTextSection";
        heading?: LocaleString;
        body?: LocaleBlockContent;
        image?: ImageWithAlt;
        imagePosition?: "left" | "right";
      }
    | {
        _key: string;
        _type: "richTextSection";
        heading?: LocaleString;
        body?: RequiredLocaleBlockContent;
      }
  > | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_BY_ANY_SLUG_QUERY
// Query: *[  _type == "page" && $slug in [slug.id, slug.en] && _id != *[_id == "siteSettings"][0].homePage._ref][0]{ slug }
export type PAGE_BY_ANY_SLUG_QUERY_RESULT = {
  slug: LocaleSlug | null;
} | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[  _type == "page" && defined(slug) && _id != *[_id == "siteSettings"][0].homePage._ref]{ slug }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: LocaleSlug | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "caseStudy" && clientConsent == true && defined(slug)]\n  | order(year desc, title.id asc){ _id, title, slug, summary, client, year }': CASE_STUDIES_QUERY_RESULT;
    '*[\n  _type == "caseStudy" && clientConsent == true && slug[$locale] == $slug\n][0]{\n  _id, title, slug, summary, client, year, challenge, approach, outcome, seo,\n  "services": services[defined(@->slug)]->{ _id, title, slug, summary },\n  "industries": industries[defined(@->slug)]->{ _id, title, slug, summary }\n}': CASE_STUDY_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "caseStudy" && clientConsent == true && $slug in [slug.id, slug.en]\n][0]{ slug }': CASE_STUDY_BY_ANY_SLUG_QUERY_RESULT;
    '*[\n  _type == "caseStudy" && clientConsent == true && defined(slug)\n]{ slug }': CASE_STUDY_SLUGS_QUERY_RESULT;
    '*[_type == "industry" && defined(slug)]\n  | order(order asc, title.id asc){ _id, title, slug, summary }': INDUSTRIES_QUERY_RESULT;
    '*[_type == "industry" && slug[$locale] == $slug][0]{\n  _id, title, slug, summary, body, seo,\n  "services": *[_type == "service" && references(^._id)] | order(order asc){ _id, title, slug, summary },\n  "caseStudies": *[_type == "caseStudy" && clientConsent == true && references(^._id)] | order(year desc){\n    _id, title, slug, summary, client, year\n  }\n}': INDUSTRY_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "industry" && $slug in [slug.id, slug.en]\n][0]{ slug }': INDUSTRY_BY_ANY_SLUG_QUERY_RESULT;
    '*[_type == "industry" && defined(slug)]{ slug }': INDUSTRY_SLUGS_QUERY_RESULT;
    '*[_type == "insight" && defined(slug)]\n  | order(publishedAt desc, _createdAt desc){ _id, title, slug, excerpt, category, publishedAt }': INSIGHTS_QUERY_RESULT;
    '*[_type == "insight" && slug[$locale] == $slug][0]{\n  _id, title, slug, excerpt, category, publishedAt, body, seo,\n  "attachmentUrl": attachment.asset->url,\n  "authors": authors[defined(@->slug)]->{ _id, name, slug, position, group, photo },\n  "services": services[defined(@->slug)]->{ _id, title, slug, summary }\n}': INSIGHT_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "insight" && $slug in [slug.id, slug.en]\n][0]{ slug }': INSIGHT_BY_ANY_SLUG_QUERY_RESULT;
    '*[_type == "insight" && defined(slug)]{ slug }': INSIGHT_SLUGS_QUERY_RESULT;
    '*[_type == "jobOpening" && isOpen == true && defined(slug)]\n  | order(_createdAt desc){ _id, title, slug, location, employmentType, deadline }': JOB_OPENINGS_QUERY_RESULT;
    '*[\n  _type == "jobOpening" && isOpen == true && slug[$locale] == $slug\n][0]{ _id, title, slug, location, employmentType, deadline, description, applyUrl, seo }': JOB_OPENING_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "jobOpening" && isOpen == true && $slug in [slug.id, slug.en]\n][0]{ slug }': JOB_OPENING_BY_ANY_SLUG_QUERY_RESULT;
    '*[\n  _type == "jobOpening" && isOpen == true && defined(slug)\n]{ slug }': JOB_OPENING_SLUGS_QUERY_RESULT;
    '*[_type == "office"]\n  | order(order asc, name.id asc){ _id, name, address, phone, email }': OFFICES_QUERY_RESULT;
    '*[_type == "person" && defined(slug)]\n  | order(order asc, name asc){ _id, name, slug, position, group, photo }': PEOPLE_QUERY_RESULT;
    '*[_type == "person" && slug[$locale] == $slug][0]{\n  _id, name, slug, position, group, photo, bio, credentials, languages, email, linkedin, seo,\n  "services": services[defined(@->slug)]->{ _id, title, slug, summary },\n  "office": office->{ name, address, phone, email },\n  "insights": *[_type == "insight" && references(^._id)] | order(publishedAt desc)[0...3]{\n    _id, title, slug, excerpt, category, publishedAt\n  }\n}': PERSON_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "person" && $slug in [slug.id, slug.en]\n][0]{ slug }': PERSON_BY_ANY_SLUG_QUERY_RESULT;
    '*[_type == "person" && defined(slug)]{ slug }': PERSON_SLUGS_QUERY_RESULT;
    '*[_type == "service" && defined(slug)]\n  | order(order asc, title.id asc){ _id, title, slug, summary }': SERVICES_QUERY_RESULT;
    '*[_type == "service" && slug[$locale] == $slug][0]{\n  _id, title, slug, summary, body, seo,\n  "keyContacts": keyContacts[defined(@->slug)]->{ _id, name, slug, position, group, photo },\n  "industries": industries[defined(@->slug)]->{ _id, title, slug, summary },\n  "caseStudies": *[_type == "caseStudy" && clientConsent == true && references(^._id)] | order(year desc){\n    _id, title, slug, summary, client, year\n  },\n  "insights": *[_type == "insight" && references(^._id)] | order(publishedAt desc)[0...3]{\n    _id, title, slug, excerpt, category, publishedAt\n  }\n}': SERVICE_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "service" && $slug in [slug.id, slug.en]\n][0]{ slug }': SERVICE_BY_ANY_SLUG_QUERY_RESULT;
    '*[_type == "service" && defined(slug)]{ slug }': SERVICE_SLUGS_QUERY_RESULT;
    '*[_id == "siteSettings"][0]{\n  organizationName, legalName, tagline, logo, footerText, disclaimer,\n  email, phone, address, socialLinks, defaultSeo\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_id == "navigation"][0]{\n  "header": header[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n },\n  "footer": footer[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n }\n}': NAVIGATION_QUERY_RESULT;
    '*[_id == "siteSettings"][0].homePage->{ \n  _id, title, slug, seo,\n  sections[]{\n    ...,\n    _type == "heroSection" => { "ctas": ctas[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } },\n    _type == "ctaSection" => { "cta": cta{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } },\n    _type == "credentialListSection" => {\n      "credentials": *[_type == "credential" && approvedForDisplay == true] | order(order asc, year desc){\n        _id, title, issuer, year, logo\n      }\n    }\n  }\n }': HOME_PAGE_QUERY_RESULT;
    '*[\n  _type == "page" && slug[$locale] == $slug && _id != *[_id == "siteSettings"][0].homePage._ref\n][0]{ \n  _id, title, slug, seo,\n  sections[]{\n    ...,\n    _type == "heroSection" => { "ctas": ctas[]{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } },\n    _type == "ctaSection" => { "cta": cta{ \n  _key, label, linkType, path, url,\n  "pageSlug": page->slug,\n  "isHomePage": defined(page._ref) && page._ref == *[_id == "siteSettings"][0].homePage._ref\n } },\n    _type == "credentialListSection" => {\n      "credentials": *[_type == "credential" && approvedForDisplay == true] | order(order asc, year desc){\n        _id, title, issuer, year, logo\n      }\n    }\n  }\n }': PAGE_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "page" && $slug in [slug.id, slug.en] && _id != *[_id == "siteSettings"][0].homePage._ref\n][0]{ slug }': PAGE_BY_ANY_SLUG_QUERY_RESULT;
    '*[\n  _type == "page" && defined(slug) && _id != *[_id == "siteSettings"][0].homePage._ref\n]{ slug }': PAGE_SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
